// examples/angular/src/app.component.ts
import { Component, ViewChild } from '@angular/core'
import { CommonModule } from '@angular/common'
import { CoverCropperComponent, type CropperState } from '@covercropper/angular'

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule, CoverCropperComponent],
  template: `
    <main>
      <h1>CoverCropper Angular</h1>
      <cover-cropper-angular #cropper [src]="sample" [aspectRatio]="16 / 9" [initialImageScale]="1.2" (valueChange)="state = $event" />
      <button type="button" (click)="exportPreview()">Export 1280px JPEG</button>
      <img *ngIf="preview" [src]="preview" alt="Export preview" width="320" />
      <pre>{{ state | json }}</pre>
    </main>
  `
})
export class AppComponent {
  @ViewChild('cropper') cropper?: CoverCropperComponent
  readonly sample = new URL('./sample.svg', import.meta.url).href
  state: CropperState | null = null
  preview = ''

  async exportPreview(): Promise<void> {
    this.preview = await this.cropper!.exportDataURL({ width: 1280, type: 'image/jpeg', quality: 0.9 })
  }
}

// examples/react-vite/src/App.tsx
import { useRef, useState } from 'react'
import { CoverCropper, type CoverCropperHandle, type CropperState } from '@covercropper/react'

const sample = new URL('./sample.svg', import.meta.url).href

export function App() {
  const cropper = useRef<CoverCropperHandle>(null)
  const [state, setState] = useState<CropperState | null>(null)
  const [preview, setPreview] = useState('')

  async function exportPreview() {
    setPreview(await cropper.current!.exportDataURL({ width: 1280, type: 'image/jpeg', quality: 0.9 }))
  }

  return (
    <main>
      <h1>CoverCropper React</h1>
      <CoverCropper ref={cropper} src={sample} aspectRatio={16 / 9} initialImageScale={1.2} onChange={(event) => setState(event.detail.state)} />
      <button onClick={exportPreview}>Export 1280px JPEG</button>
      {preview && <img src={preview} alt="Export preview" width={320} />}
      <pre>{JSON.stringify(state, null, 2)}</pre>
    </main>
  )
}
